### PR TITLE
Refactor/reduce nesting and fix hookPayload per document

### LINKED ISSUE #579: Multiplexing closes connection on auth failed
**Description**
I'm using the same WS connection to connect to multiple documents.

For document A, I don't have access (I provide an invalid token)
For document B, I do have access.

As soon as I connect to document A, the websocket connection is closed.

**Expected behavior**
In a multiplexing environment where auth is document based, I'd expect the architecture to be completely independent. Anything I do with document A should be unrelated to what I do with document B and vice versa

### PR DESCRIPTION
**Pull request by YousefED**
This refactor:
- reduces the nesting in ClientConnection.ts by extracting inline functions to class members
- fixes #579 (and adds the tests from https://github.com/ueberdosis/hocuspocus/pull/613), by making hookPayload document specific

### CODE REVIEW

File: packages/server/src/Hocuspocus.ts [hunk 1]
```diff
@@ -372,8 +373,8 @@ export class Hocuspocus {
    * … and if nothings fails it’ll fully establish the connection and
    * load the Document then.
    */
-  handleConnection(incoming: WebSocket, request: IncomingMessage, context: any = null): void {
-    const clientConnection = new ClientConnection(incoming, request, context, this, this.hooks.bind(this), this.debugger, {
+  handleConnection(incoming: WebSocket, request: IncomingMessage): void {
+    const clientConnection = new ClientConnection(incoming, request, this, this.hooks.bind(this), this.debugger, {
```
Comment (janthurau) [inline packages/server/src/Hocuspocus.ts:377]: Can we inject `context` into clientConnection.hookPayload.context? Otherwise this would be a BC change if used in Express or another framework

**Review by janthurau — COMMENTED** [review]
Thanks again @YousefED! :)
