### PR TITLE
Efficiently route messages through HocuspocusProviderWebsocket

### LINKED ISSUE #724: onMessage is inefficiently called on every Doc
**The problem I am facing**
When multiplexing many Docs over a single `HocuspocusProviderWebsocket`, every message is handled by every `HocuspocusProvider`. Every `HocuspocusProvider` reads and writes the documentName in order to see if it is the intended recipient. 

With hundreds of Docs, this results in excessive CPU usage. It can also result in an out-of-memory crash, because as messages pile up, more and more messages are decoded and stored in memory without time for gc to kick in (reproducible).

**The solution I would like**
The main way to alleviate the issue would be to have a single onMessage handler that decodes the documentName and then routes the message to the appropriate `HocuspocusProvider`. This would also improve memory usage by dramatically reducing the number of listeners. 

It is also possible to perform a more efficient documentName comparison (without reading and re-writing the message), but this is minor compared to the listener consolidation. 

**Alternatives I have considered**
None

**Additional context**
I can attempt a PR, but I wanted to post here first and get your input.

### PR DESCRIPTION
**Pull request by raineorshine**
This PR changes the provider's onMessage running time from O(n) to O(1), where n is the number of all attached providers. It does this by adding a Map to the `HocuspocusProviderWebsocket` configuration that allows O(1) lookup of attached providers by document name. It will then manually call onMessage on the appropriate provider and only that provider. 

Fixes #724

### CODE REVIEW

**Comment by raineorshine** [comment]
I still need to test in the playground and my app, but it should be okay. Ended up being a very simple change.

File: packages/provider/src/HocuspocusProvider.ts [hunk 1]
```diff
@@ -447,10 +443,6 @@ export class HocuspocusProvider extends EventEmitter {
 
     const documentName = message.readVarString()
 
-    if (documentName !== this.configuration.name) {
-      return // message is meant for another provider
-    }
-
     message.writeVarString(documentName)
```
Comment (raineorshine) [inline packages/provider/src/HocuspocusProvider.ts:446]: As an aside, I'm not sure why it is required to read the documentName now that this function does not use it. However, removing the read and write breaks the message. I even tried messing around with the encoder and decoder positions but could not get it to work without leaving the read + write as-is. There is clearly a side effect here that I do not understand.

Comment (janthurau) [reply packages/provider/src/HocuspocusProvider.ts:446]: yea, that won't work because of the position. You'd need to manually read the first byte, and then move the pointer by the value of it (first byte contains the length of the string). I guess we can keep it like this though, the performance impact should be neglectable.

**Comment by janthurau** [comment]
Thanks a lot for this! Looks great, will do a round of testing as well and then get this merged 😎
